
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 05 13:06:26 CET 2016
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LICZBA = 21;
  public static final int PKLAMRA = 14;
  public static final int RYSUJ = 9;
  public static final int PLUS = 2;
  public static final int PRZECINEK = 4;
  public static final int JESLI = 19;
  public static final int LKLAMRA = 13;
  public static final int APOSTROF = 7;
  public static final int ID = 22;
  public static final int MNIEJSZE = 18;
  public static final int WIEKSZE = 17;
  public static final int ZMIENNE = 11;
  public static final int PNAWIAS = 6;
  public static final int EOF = 0;
  public static final int ROWNE = 15;
  public static final int PETLA = 20;
  public static final int NIEROWNE = 16;
  public static final int PRZYPISZ = 12;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int START = 8;
  public static final int KONIEC = 10;
  public static final int LNAWIAS = 5;
}

